name: PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    uses: ./.github/workflows/build.yml
  DEV:
    uses: ./.github/workflows/deploy.yml
    needs: Build
    with:
      environment: DEV
    secrets: inherit
